const YAML = require('json-to-pretty-yaml');
const fs = require("fs")

const generator = require("../src/index")
if(!generator){
	console.log("Make sure to place a index.js file in the src folder with a default export of a function that returns a DockerCompose!")
	process.exit(1)
}

const dockerCompose = generator()

const result = YAML.stringify(dockerCompose.toObject())
const comment = `
COMPOCOMPO Autogenerated file
${new Date()}`
  .replaceAll("\n", "\n# ")

fs.writeFileSync("out/compose.yml", comment + result)